manifest_version = "1"
id = "http-csharp"
description = "HTTP request handler using C# (EXPERIMENTAL)"

[parameters]
project-description = { type = "string", prompt = "Project description", default = "" }
http-base = { type = "string", prompt = "HTTP base", default = "/", pattern = "^/\\S*$" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
